

#include <iostream>
#include <cmath>
using namespace std;

void PythagoreanTriple(int m, int n, int& a, int& b, int& c) {
    a = pow(m, 2) - pow(n, 2); // calculate a using the given formula
    b = 2 * m * n; // calculate b using the given formula
    c = pow(m, 2) + pow(n, 2); // calculate c using the given formula
}

int main() {
    int m, n, a, b, c;
    cout << "Enter values for m and n (m > n): ";
    cin >> m >> n;
    PythagoreanTriple(m, n, a, b, c);
    cout << "The Pythagorean triple generated by m = " << m << " and n = " << n << " is (" << a << ", " << b << ", " << c << ")." << endl;
    return 0;
}

